name: 'Install OSQP (Octave)'
description: 'Build and install Octave interface for OSQP'
author: 'Ray Zimmerman'

inputs:
  cached:
    description: 'true means installing from a cached build'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    # expects that Octave has already been installed
    - name: Build OSQP
      run: |
        export OSQP_TAG=v0.6.2
        export OSQP_MATLAB_TAG=master
        export OSQP_PATH=$HOME/build/osqp-matlab
        ${{ inputs.cached }} && echo "cached - skip build" || echo "Not cached - build it"
        ! ${{ inputs.cached }} && [ ! -d $HOME/build ] && mkdir -p $HOME/build
        ! ${{ inputs.cached }} && cd $HOME/build
        ! ${{ inputs.cached }} && git clone -b ${OSQP_TAG} --recursive https://github.com/oxfordcontrol/osqp
        ! ${{ inputs.cached }} && git clone -b ${OSQP_MATLAB_TAG} --recurse-submodules https://github.com/oxfordcontrol/osqp-matlab
        ! ${{ inputs.cached }} && mkdir -p $HOME/build/osqp/build
        ! ${{ inputs.cached }} && [ ! -d $HOME/install ] && mkdir -p $HOME/install
        ! ${{ inputs.cached }} && cd $HOME/build/osqp/build
        ! ${{ inputs.cached }} && cmake -DCMAKE_INSTALL_PREFIX=$HOME/install -G "Unix Makefiles" ..
        ! ${{ inputs.cached }} && cmake --build .
        ! ${{ inputs.cached }} && cmake --install .
        echo "OSQP_PATH=${OSQP_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Build and install OSQP Octave interface
      run: |
        ! ${{ inputs.cached }} && ln -s /usr/include/octave-${OCTAVE_VER}/octave/Matrix.h $HOME/install/include/osqp/matrix.h
        ! ${{ inputs.cached }} && ls -al $HOME/install/include/osqp
        ! ${{ inputs.cached }} && cd $HOME/build/osqp-matlab
        ! ${{ inputs.cached }} && $ML_CMD "mex -I$HOME/install/include/osqp  -I$HOME/install/include/qdldl -I$HOME/build/osqp/lin_sys/direct/qdldl osqp_mex.cpp $HOME/install/lib/libosqp.a"
        ! ${{ inputs.cached }} && ls -al
        echo "$ML_CMD \"addpath('${OSQP_PATH}'); savepath\""
        $ML_CMD "addpath('${OSQP_PATH}'); savepath"
      shell: bash

branding:
  icon: 'zap'
  color: 'yellow'
